### ISSUE TITLE
Infinite navigation

### ISSUE THREAD

**Issue by artyorsh** [bmcmahen/react-cube-navigation#3]
I think some people would be interested in how to implement infinite navigation, so after 5 minutes of playing with this, I've got [this solution](https://codesandbox.io/s/react-cube-navigation-infinite-example-63osv) :)

Nice lib btw 👍

**Comment by bmcmahen** [comment]
Thanks @artyorsh ! One thing this library doesn't really handle all that well is jumping to random indexes (beyond next or previous). You can see that in your example, actually, because if it skips back to the first pane you can actually gesture left and it kinda glitches. 

The main codesandbox example I have is kinda infinite in a sense. You could easily fetch more images once the index reaches a bit higher and append them to the images array. So you could basically keep swiping right indefinitely by fetching more and more images.

I am going to close this for now but will open an issue for handling skipping to random indexes
